Task: create a repo. Executor: Oleksii Bashkirov
OleksiiBashkirov/online-book-store pull request #1
Opened 2024-07-08 13:38 UTC by OleksiiBashkirov

Created the Book entity, repository and service;
Also created the OnlineBookStoreApplication class with the main method;
Added application.properties file for database configuration.
Configured Checkstyle and Continuous Integration (CI) using GitHub Actions.
Added H2 database configuration for testing purposes.

2024-07-08 14:23 UTC, Elena-Bruyako requested changes
You must merge you changes to master only when mentor approve them

2024-07-08 14:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Book.java
> +    //comment
remove 

```
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
```

2024-07-08 14:33 UTC, OleksiiBashkirov commented
> You must merge you changes to master only when mentor approve them

Yes, thanks for the guidance. Initially, I committed and pushed changes directly to the main branch. After realizing that I should have used a different branch, I corrected the workflow by creating the book-entity branch for the changes. Moving forward, I will ensure to wait for your approval before merging any changes to the main branch. Thank you for your understanding and support.

2024-07-09 06:30 UTC, OleksiiBashkirov commented
I have reset the "main" branch to ensure it only contains approved commits. All changes are now correctly placed in the "book-entity" branch, and I will await your approval before merging any changes to the "main" branch moving forward.
Thank you for your guidance.

2024-07-10 07:19 UTC, MAMentorFX approved these changes

2024-07-10 07:19 UTC, MAMentorFX commented on .mvn/wrapper/maven-wrapper.properties
> +# Licensed to the Apache Software Foundation (ASF) under one
I believe this also should be in gitignore

2024-07-10 07:19 UTC, MAMentorFX commented on src/main/resources/application.properties
> +#comment
```suggestion
```

2024-07-10 09:39 UTC, OleksiiBashkirov commented on .mvn/wrapper/maven-wrapper.properties
> +# Licensed to the Apache Software Foundation (ASF) under one
Hi, thanks. I have updated the ".gitignore" file to exclude the ".mvn" directory and removed the ".mvn" directory from the repository as per your suggestion.
Thank you for your guidance.

2024-07-10 09:40 UTC, merged