Task: Spring boot practice. Add Category model. Executor: Oleksii Bashkirov.
OleksiiBashkirov/online-book-store pull request #10
Opened 2024-07-30 08:45 UTC by OleksiiBashkirov

feat: Added support for Category entity and related functionalities

- Added `Category` entity
- Updated `Book` class to include `private Set<Category> categories = new HashSet<>()`
- Added method to `BookRepository`: findAllByCategoryId

- Implemented `CategoryRepository` interface using `JpaRepository`
- Implemented DTO classes for `Category` entity
- Modified `BookMapper` class:
  - Added `BookDtoWithoutCategoryIds toDtoWithoutCategories(Book book)`
  - Added `@AfterMapping default void setCategoryIds(@MappingTarget BookDto bookDto, Book book)`

- Added `CategoryMapper` class:
  - Added `CategoryDto toDto(Category category)`
  - Added `Category toModel(CategoryDto categoryDTO)`

- Implemented `CategoryService` interface and `CategoryServiceImpl` class:
  - Added `List<CategoryDto> findAll()`
  - Added `CategoryDto getById(Long id)`
  - Added `CategoryDto save(CategoryDto categoryDto)`
  - Added `CategoryDto update(Long id, CategoryDto categoryDto)`
  - Added `void deleteById(Long id)`

- Added `CategoryController` class:
  - Added `CategoryDto createCategory(CategoryDto categoryDto)`
  - Added `List<CategoryDto> getAll()`
  - Added `CategoryDto getCategoryById(Long id)`
  - Added `CategoryDto updateCategory(Long id, CreateCategoryRequestDto requestDto)`
  - Added `void deleteCategory(Long id)`
  - Added `Page<BookDtoWithoutCategoryIds> getBooksByCategoryId(Long id)`

- Added Pagination, Sorting, and Swagger to all controllers
- Used Liquibase for database versioning and implement soft delete approach for entities

2024-07-30 12:11 UTC, Elena-Bruyako requested changes
see comments

2024-07-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/config/SecurityConfig.java
> +                                .requestMatchers(
you don't need these changes

2024-07-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/book/BookDtoWithoutCategoryIds.java
> +    private boolean isDeleted;
```suggestion
```

2024-07-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/category/CategoryDto.java
> +    private boolean isDeleted;
```suggestion
```

2024-07-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/user/UserLoginResponseDto.java
> +    public UserLoginResponseDto(String token) {
remove

2024-07-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Book.java
> +            name = "book_category",
```suggestion
            name = "books_categories",
```

2024-07-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Category.java
> +    @NotNull
```suggestion
    @Column(nullable = false, unique = true)
```

2024-07-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Category.java
> +    private Set<Book> books = new HashSet<>();
remove

2024-07-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-07-30 12:11 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/CategoryServiceImpl.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-07-30 12:11 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/db.changelog-7.0.yaml
> +databaseChangeLog:
Where is books-categories table?

2024-08-02 11:32 UTC, okuzan requested changes

2024-08-02 11:32 UTC, okuzan commented on src/main/java/mate/academy/service/impl/CategoryServiceImpl.java
> +                );
repeated logic, extract to a private method

2024-08-02 11:32 UTC, okuzan commented on src/main/java/mate/academy/model/Category.java
> +@SQLRestriction(value = "is_deleted = false")
```suggestion
@SQLDelete(sql = "UPDATE categories SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction(value = "is_deleted = FALSE")
```

2024-08-04 15:45 UTC, Elena-Bruyako requested changes
see comments

2024-08-04 15:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/AuthenticationController.java
> +    public String login(@RequestBody @Valid UserLoginRequestDto requestDto) {
Why did you decide to change it?

2024-08-04 15:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/CategoryController.java
> +    public List<CategoryDto> getAll() {
```suggestion
    public List<CategoryDto> getAll(@ParameterObject @PageableDefault Pageable pageable) {
```

2024-08-04 15:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/book/BookDto.java
> +    private boolean isDeleted;
```suggestion
```

2024-08-05 04:50 UTC, OleksiiBashkirov commented on src/main/java/mate/academy/controller/AuthenticationController.java
> +    public String login(@RequestBody @Valid UserLoginRequestDto requestDto) {
Hi Elena,

Thank you for your feedback. I wanted to clarify that the changes you mentioned were not intentional. I believe they might have occurred during a merge conflict resolution or while pushing code to GitHub. I’ve since reviewed the affected files and corrected the unintended modifications to ensure they align with the intended functionality.

login Method Return Type: The change in the AuthenticationController was accidental. I've reverted it back to `String` as it was supposed to be.

getAll Method Signature: In the CategoryController, the missing Pageable parameter was not a deliberate change. I’ve added the @ParameterObject @PageableDefault Pageable pageable back to the method signature.

BookDto Field: The presence of the private boolean isDeleted field was also unintentional. I've removed this redundant field.

I've made the necessary corrections to address these issues.
Thank you for pointing them out, and I appreciate your guidance in maintaining the quality of code.

2024-08-06 18:19 UTC, sarakhmen approved these changes

2024-08-07 05:43 UTC, merged