Task: Spring Boot Portfolio Project — Part 10.Add Order model. Executor: Oleksii Bashkirov.
OleksiiBashkirov/online-book-store pull request #14
Opened 2024-07-31 12:26 UTC by OleksiiBashkirov

feat: Implement Order and OrderItem entities with soft delete and relationships

- Created Order and OrderItem entities
- Implemented relationships for Order and OrderItem entities
- Added soft delete functionality to Order entity
- Created OrderRepository and OrderItemRepository
- Implemented OrderService and OrderServiceImpl
- Added endpoints for managing orders and order items in OrderController
- Updated Liquibase changelog files:
  - Renamed changelog files for better understanding of their contents
  - Split categories and books_categories tables into separate changelog files

2024-08-02 13:00 UTC, okuzan requested changes

2024-08-02 13:00 UTC, okuzan commented on src/main/java/mate/academy/service/impl/OrderServiceImpl.java
> +                                + orderId));
repreated logic , extract to a private method

2024-08-02 13:00 UTC, okuzan commented on src/main/java/mate/academy/model/Order.java
> +@SQLRestriction(value = "is_deleted = false")
```suggestion
@SQLDelete(sql = "UPDATE orders SET is_deleted = TRUE WHERE id = ?")
@SQLRestriction(value = "is_deleted = FALSE")
```

2024-08-06 10:44 UTC, MentorMateAcademy requested changes

2024-08-06 10:44 UTC, MentorMateAcademy commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +        shoppingCartService.addToCart(userPrincipal.getUser().getId(),request.getBookId(),
```suggestion
        shoppingCartService.addToCart(userPrincipal.getUser().getId(), request.getBookId(),
```

2024-08-06 10:44 UTC, MentorMateAcademy commented on src/main/java/mate/academy/controller/ShoppingCartController.java
> +        shoppingCartService.addToCart(userPrincipal.getUser().getId(),request.getBookId(),
formatting code

2024-08-06 10:44 UTC, MentorMateAcademy commented on src/main/java/mate/academy/repository/BookRepository.java
>  @Repository
```suggestion
```

2024-08-06 10:44 UTC, MentorMateAcademy commented on src/main/java/mate/academy/repository/BookRepository.java
>  @Repository
this anno is redundant

2024-08-06 10:44 UTC, MentorMateAcademy commented on src/main/java/mate/academy/repository/BookRepositoryCustomImpl.java
> +        var cq = cb.createQuery(Book.class);
short naming is bad practice

2024-08-06 10:44 UTC, MentorMateAcademy commented on src/main/java/mate/academy/service/impl/OrderServiceImpl.java
> +        var order = getOrder(orderId);
What profit of using var here?

2024-08-06 10:44 UTC, MentorMateAcademy commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
>      }
private methods after public

2024-08-06 10:44 UTC, MentorMateAcademy commented on src/main/java/mate/academy/service/impl/ShoppingCartServiceImpl.java
> +    private static CartItem createCartItem(int quantity, ShoppingCart cart, Book book) {
Why do you need static?

2024-08-06 19:07 UTC, sarakhmen approved these changes

2024-08-07 07:03 UTC, merged