Task: Spring Boot Portfolio Project — Part 3. Executor: Oleksii Bashkirov.
OleksiiBashkirov/online-book-store pull request #3
Opened 2024-07-23 08:14 UTC by OleksiiBashkirov

feat: Integrate Liquibase, implement JPA repository and soft delete
- Replaced BookRepository with JpaRepository implementation.
- Added Liquibase support for database versioning.
- Changed spring.jpa.hibernate.ddl-auto property value to validate.
- Implemented soft delete functionality in the Book entity.
- Added missing endpoints and methods in BookService.
- Updated BookController to handle new endpoints:
  - GET /api/books
  - GET /api/books/{id}
  - POST /api/books
  - PUT /api/books/{id}
  - DELETE /api/books/{id}
- Updated database schema to use BIT(1) for boolean values.
- Ensured proper integration and testing with Postman.

2024-07-23 08:34 UTC, Elena-Bruyako requested changes
Let's improve your solution

2024-07-23 08:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Book.java
> +@Where(clause = "is_deleted = false")
`@Where` is deprecated, use `@SQLRestriction`

2024-07-23 08:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +                .filter(b -> !b.isDeleted())
```suggestion
```

2024-07-23 08:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +                .filter(b -> !b.isDeleted())
```suggestion
```

2024-07-23 08:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +        book.setTitle(requestDto.getTitle());
use MapStruct for this logic

2024-07-23 08:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +        bookRepository.save(book);
```suggestion
        bookRepository.deleteById(id);
```

2024-07-23 08:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/BookServiceImpl.java
> +                .filter(book -> !book.isDeleted())
```suggestion
```

2024-07-24 10:38 UTC, MentorMateAcademy approved these changes

2024-07-25 03:38 UTC, merged