Task: Spring Boot Portfolio Project — Part 6. Executor: Oleksii Bashkirov.
OleksiiBashkirov/online-book-store pull request #8
Opened 2024-07-26 12:22 UTC by OleksiiBashkirov

feat: Incorporate Spring Security with Role-based Access Control

- Added `spring-boot-starter-security` to the project.
- Created `SecurityConfig` class with `PasswordEncoder` and `SecurityFilterChain` beans.
- Implemented `UserDetails` in `User` class and `UserDetailsService`.
- Made `/auth/registration` publicly available.
- Added `Role` entity and `RoleRepository`.
- Added `Set<Role> roles` field to `User` entity.
- Updated Liquibase changesets for roles and user roles.
- Secured endpoints with `@PreAuthorize` based on roles.

2024-07-26 18:09 UTC, MentorMateAcademy requested changes

2024-07-26 18:09 UTC, MentorMateAcademy commented on src/main/java/mate/academy/repository/RoleRepository.java
> +@Repository
```suggestion
```

2024-07-27 08:22 UTC, Elena-Bruyako requested changes
see comments

2024-07-27 08:22 UTC, Elena-Bruyako commented on pom.xml
> +            <version>3.3.0</version>
```suggestion
```

2024-07-27 08:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/config/SecurityConfig.java
> +@Configuration
```suggestion
@Configuration
@EnableMethodSecurity
```

2024-07-27 08:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/config/SecurityConfig.java
> +            )
add userDetailsService

2024-07-27 08:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany
```

2024-07-27 08:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("User not found."));
```suggestion
{
        return userRepository.findByEmail(username)
                .orElseThrow(() -> new EntityNotFoundException("User not found."));
```

2024-07-27 08:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/UserServiceImpl.java
> +        user.setPassword(passwordEncoder.encode(requestDto.getPassword()));
find role by name add it to roles

2024-07-27 18:25 UTC, sarakhmen requested changes
let`s improve your sokution

2024-07-27 18:25 UTC, sarakhmen commented on src/main/java/mate/academy/security/CustomUserDetailsService.java
> +        System.out.println("User roles: " + user.getRoles());
remove these debug messages

2024-07-28 05:00 UTC, OleksiiBashkirov commented on src/main/java/mate/academy/security/CustomUserDetailsService.java
> +        System.out.println("User roles: " + user.getRoles());
Thank you for pointing that out. 
I had accidentally left those debug messages in, but I have now removed them.
Thank you for your guidance!

2024-07-28 16:43 UTC, Elena-Bruyako requested changes
see comments

2024-07-28 16:43 UTC, Elena-Bruyako commented on src/main/java/mate/academy/config/SecurityConfig.java
> +@EnableMethodSecurity
Do you need both of these annotations `@EnableWebSecurity and @EnableMethodSecurity`?

2024-07-28 16:43 UTC, Elena-Bruyako commented on src/main/java/mate/academy/mapper/BookMapper.java
> +@Component
```suggestion
```

2024-07-28 16:43 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/User.java
> +    @ManyToMany()
```suggestion
    @ManyToMany
```

2024-07-28 16:43 UTC, Elena-Bruyako commented on src/main/java/mate/academy/security/CustomUserDetailsService.java
> +        );
```suggestion
           {

        return userRepository.findByEmail(username)
                .orElseThrow(() -> new EntityNotFoundException("User not found: " + username));
```

2024-07-28 16:43 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/impl/UserServiceImpl.java
> +        user.setRoles(Collections.singleton(userRole));
or you can use Set.of()

2024-07-29 08:48 UTC, Elena-Bruyako approved these changes
well done

2024-07-29 12:45 UTC, merged

2024-07-29 13:35 UTC, OleksiiBashkirov commented
Please disregard the last pull request in this theme made through the mate.academy platform. 
Due to an accidental click, I submitted changes meant for the "JWT" theme under the "Spring Boot Security" theme. 
Sorry about that!