Spring Boot Portfolio Project — Part 7. JWT. Executor: Oleksii Bashkirov.
OleksiiBashkirov/online-book-store pull request #9
Opened 2024-07-29 12:41 UTC by OleksiiBashkirov

feat: Implement JWT authentication

- Added `login(UserLoginRequestDto request)` method to `AuthenticationController`.
- Created `AuthenticationService`, `JwtAuthenticationFilter`, and `JwtUtil` classes.
- Made `/auth/login` endpoint publicly accessible.
- Configured `SecurityFilterChain` to use the new JWT filter.
- Implemented data validation for new DTO classes.

2024-07-29 12:49 UTC, Elena-Bruyako requested changes
see comments

2024-07-29 12:49 UTC, Elena-Bruyako commented on pom.xml
> +
remove empty lines

2024-07-29 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/config/JwtConfig.java
> +public class JwtConfig {
Why do you need this?

2024-07-29 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/config/SecurityConfig.java
> +    @Bean
This confi could be much simplier
```suggestion
    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        return http
                .cors(AbstractHttpConfigurer::disable)
                .csrf(AbstractHttpConfigurer::disable)
                .authorizeHttpRequests(
                        auth -> auth
                                .requestMatchers(
                                        antMatcher("/auth/**"),
                                        antMatcher("/swagger-ui/**"),
                                        antMatcher("/v3/api-docs/**"))
                                .permitAll()
                                .anyRequest()
                                .authenticated()
                )
                .sessionManagement(
                        s -> s.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
                .addFilterBefore(jwtAuthFilter,
                        UsernamePasswordAuthenticationFilter.class)
                .userDetailsService(service)
                .build();
    }

    @Bean
    public AuthenticationManager authenticationManager(
            AuthenticationConfiguration authenticationConfiguration) throws Exception {
        return authenticationConfiguration.getAuthenticationManager();
    }
```

2024-07-29 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/config/SwaggerConfig.java
> +                .components(new Components().addSecuritySchemes("BearerAuth",
create constant for "BearerAuth"

2024-07-29 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/UserLoginResponseDto.java
> +@AllArgsConstructor
```suggestion
```

2024-07-29 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/repository/UserRepository.java
> +    Optional<User> findByEmail(String email);
```suggestion
    @EntityGraph(attributePaths = "roles")
    Optional<User> findByEmail(String email);
```

2024-07-29 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/security/JwtAuthenticationFilter.java
> +        String bearerToken = httpServletRequest.getHeader("Authorization");
```suggestion
        String bearerToken = httpServletRequest.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-07-29 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Create constant for "Bearer "

2024-07-29 12:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
```suggestion
            return bearerToken.substring(constant.length());
```

2024-07-29 13:32 UTC, OleksiiBashkirov commented
I wanted to apologize for my recent accidental pull request to https://github.com/OleksiiBashkirov/online-book-store/pull/8. 
Due to an accidental click, I submitted the changes meant for the "JWT" theme under the "Spring Boot Security" theme.
Sorry about that. Please disregerd that pull request.
Thank you for your understanding and patience!

2024-07-29 19:03 UTC, MentorMateAcademy requested changes

2024-07-29 19:03 UTC, MentorMateAcademy commented on src/main/java/mate/academy/config/SwaggerConfig.java
> +                                .bearerFormat("JWT")))
you can save to constant too

2024-07-30 09:49 UTC, MentorMateAcademy approved these changes

2024-07-30 11:21 UTC, Elena-Bruyako requested changes
This branch has conflicts, please fix them

2024-07-30 11:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/AuthenticationController.java
> +    @PostMapping("/login")
Add swagger annotations

2024-07-30 11:40 UTC, merged